#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 

bspc config border_width         1
bspc config window_gap          20
bspc config active_border_color #0000FF 
bspc config normal_border_color #000080


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

setxkbmap br &
nitrogen --restore &
picom -f & 
/home/burddan/.config/polybar/launch.sh --docky &
wmname LG3D &
bspc rule -a android-studio state=floating border=off follow=on
